### ISSUE TITLE
Nexus will not compile using Ubuntu 22.04

### ISSUE THREAD

**Issue by ThomasRScott** [Nexusoft/LLL-TAO#90]
Compiling src/LLC/eckey.cpp
In file included from /usr/include/openssl/asn1.h:33,
                 from /usr/include/openssl/ec.h:92,
                 from /usr/include/openssl/ecdsa.h:10,
                 from src/LLC/eckey.cpp:16:
src/LLC/eckey.cpp: In function ‘int LLC::ECDSA_SIG_recover_key_GFp(EC_KEY*, BIGNUM*, BIGNUM*, const unsigned char*, int, int, int)’:
src/LLC/eckey.cpp:197:13: error: could not convert ‘BN_zero_ex(zero)’ from ‘void’ to ‘bool’
  197 |         if(!BN_zero(zero))
      |             ^~~~~~~
      |             |
      |             void
src/LLC/eckey.cpp:197:13: error: in argument to unary !
make: *** [makefile.cli:1262: build/LLC_eckey.o] Error 1

**Comment by VidereLicet** [comment]
What version of openssl are you using? 1.1.1?
